### ISSUE TITLE
minor API suggestions

### ISSUE THREAD

**Issue by rogpeppe** [dgryski/go-sequitur#2]
Just after a once-over of the API:

Given that you can't call Parse on a Grammar more than once, why not:

    func Parse(str []byte) *Grammar

rather than having Parse as a method on Grammar? Then there's no need to have ErrNoParsedGrammar and ErrAlreadyParsed.

Also, it would be nice to have a way of getting the resulting grammar as a Go data structure rather than being forced to parse it from the output of PrettyPrint.

**Comment by dgryski** [comment]
I agree having `Parse` as the constructor is probably nicer.  Not sure why I made it a method on `Grammar`.  Probably just over zealous cleanup when I was moving away from the C++ style.

**Comment by elliott5** [comment]
To finish implementing this API suggestion the `Print` and `PrettyPrint` methods would need to return `nil` rather than `ErrNoParsedGrammar` on finding an empty grammar. I'd imagine `Print()` would print nothing out, while `PrettyPrint()` would just print "->". Both `ErrNoParsedGrammar` and `ErrEmptyInput` would then be redundant.

There are also some changes I'd need to make to the accessor functions for "empty input in -> empty grammar out" to be implemented. I'll go ahead and make those now as part of PR #5 .
Edit: now done.

**Comment by elliott5** [comment]
@dgryski  I notice that your `fuzz.go` contains the line `g := Parse(data)` ... so I think we are all agreed.

Edit: now done in PR #5 .

**Comment by elliott5** [comment]
No more to do here I hope.
